data:
  block_size: 240
  duration: 2
  sampling_rate: 24000
  train_path: ./datasets/gin
  valid_path: ./datasets/gin
device: cuda
env:
  expdir: exp/f1-full/full-256
  gpu: 0
  gpu_id: 0
inference:
  batch_size: 1
loss:
  n_ffts:
  - 1024
  - 512
  - 256
  - 128
model:
  n_harmonics: 150
  n_mag_harmonic: 256
  n_mag_noise: 80
train:
  batch_size: 16
  epochs: 100000
  interval_log: 10
  interval_save: 500
  interval_val: 500
  lr: 0.002
