# configs/svs_formant.yaml

data:
  block_size: 240
  duration: 2
  sampling_rate: 24000
  train_path: ./datasets
  valid_path: ./datasets

model:
  n_mag_harmonic: 256
  n_mag_noise: 80
  n_harmonics: 150
  n_formants: 5
  pseudo_mel_dim: 80
  pseudo_mel_hidden: 64
  formant_hidden: 32
  num_phonemes: 100  # This should be updated based on your dataset
  num_singers: 10    # This should be updated based on your dataset
  num_languages: 5   # This should be updated based on your dataset

loss:
  n_ffts: [1024, 512, 256, 128]

device: cuda

env:
  expdir: exp/svs_formant
  gpu: 0
  gpu_id: 0

inference:
  batch_size: 1

train:
  batch_size: 16
  epochs: 1000000
  interval_log: 100  # step
  interval_save: 1   # epoch
  interval_val: 1    # epoch
  lr: 0.0005         # lower learning rate compared to DDSP